name: Website
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: 🧰 Install WASM Target
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
          version: 'latest'

      - name: Build
        run: trunk build --release --public-url type-id-gen

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1